### ISSUE TITLE
Buffer RangeError in Node.js

### ISSUE THREAD

**Issue by guybedford** [patrickkunka/bandwidth-throttle-stream#15]
This project looks good, it's hard to find one that throttles evenly. Unfortunately I'm getting the following error with a simple setup of 750000 bytes per second using it in a server response stream:

```
RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at BandwidthThrottle.transform (C:\Users\Guy\Projects\es-module-shims\node_modules\bandwidth-throttle-stream\dist\BandwidthThrottle.js:135:33)
    at transform (C:\Users\Guy\Projects\es-module-shims\node_modules\bandwidth-throttle-stream\dist\BandwidthThrottle.js:54:40)
    at BandwidthThrottle.transform [as _transform] (C:\Users\Guy\Projects\es-module-shims\node_modules\bandwidth-throttle-stream\dist\BaseTransformStream\BaseTransformStream.node.js:17:17)
    at BandwidthThrottle.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at BandwidthThrottle.Writable.end (node:internal/streams/writable:610:17)
    at Http2SecureServer.<anonymous> (file:///C:/Users/Guy/Projects/es-module-shims/bench/http2-server.js:89:16)
```

**Comment by guybedford** [comment]
Ah I see a known content length is expected, unfortunately that's not possible for a lot of streaming use cases.

**Comment by guybedford** [comment]
(if I try to reserve extra space it stalls the connection, so it seems the expectation is that this is exact)

**Comment by guybedford** [comment]
I ended up going with this implementation instead:

```js
class ThrottleGroup {
  chunks = [];
  constructor ({ rate, interval = 10 }) {
    this.tickRoom = rate / (1000 / interval);
    this.nextTick = performance.now() + interval;
    const checkFn = () => {
      if (performance.now() > this.nextTick) {
        this.tick();
        this.nextTick = this.nextTick + interval;
      }
      setImmediate(checkFn);
    };
    setImmediate(checkFn);
  }
  throttle () {
    return new ThrottleTransform(this);
  }
  tick () {
    let tickRoom = this.tickRoom;
    let next;
    while (next = this.chunks.shift()) {
      const { chunk, callback, stream } = next;
      if (chunk === null) {
        callback();
        continue;
      }
      if (chunk.byteLength > tickRoom) {
        stream.push(chunk.slice(0, tickRoom));
        this.chunks.unshift({ chunk: chunk.slice(tickRoom), callback, stream });
        tickRoom = 0;
      } else {
        tickRoom -= chunk.byteLength;
        callback(null, chunk);
      }
      if (tickRoom === 0)
        break;
    }
  }
}
class ThrottleTransform extends Transform {
  constructor(group) {
    super();
    this.group = group;
  }
  _transform (chunk, _encoding, callback) {
    this.group.chunks.push({ chunk, callback, stream: this });
  }
  _flush (callback) {
    this.group.chunks.push({ chunk: null, callback, stream: null });
  }
}
